### ISSUE TITLE
Can't repeat download

### ISSUE THREAD

**Issue by ssh-keyz** [modmii/modmii.github.io#10]
"R" and "r" fail to repeat the download 

<img width="785" alt="Screenshot 2024-04-11 at 8 37 58 PM" src="https://github.com/modmii/modmii.github.io/assets/17808066/fb07a0cb-ba7c-45b7-a35e-03c004931bb7">

**Comment by xflak** [comment]
Can u please share what your queue was on the first attempt so I can try to replicate it?
