### ISSUE TITLE
neek2o rev96 not installed properly

### ISSUE THREAD

**Issue by kerimugurdonmez** [modmii/modmii.github.io#11]
Hello,
I couldn't build an emuNAND for the wii.
All programs downloaded without any problems. Have the servers of this thing called neek2o been shut down? Or is there a problem?
I would be glad if you help...
Thank you from now...

<img width="460" alt="Ekran görüntüsü 2024-07-07 113156" src="https://github.com/modmii/modmii.github.io/assets/28684471/1cbed362-0856-468b-9989-c1a6adb0e0bb">

**Comment by xflak** [comment]
Known bug, already fixed in the beta version, but in the meantime it can be fixed by following the steps at the bottom of the first post here
https://gbatemp.net/threads/best-way-to-mod-any-wii-modmii-for-windows-official-support-thread.207126/
