### ISSUE TITLE
translation question

### ISSUE THREAD

**Issue by Vilagamer999** [modmii/modmii.github.io#2]
Hey xflak I would like to continue translating the Spanish version of modmii.

**Comment by xflak** [comment]
It's a big task that would require lots of work, but if you are willing, I will support you in this endeavor and make it an official release if/when it's ready! Let's discuss more in private

**Comment by Wiener234** [comment]
Hey xflak would you consider putting some guide out for people who want to translate modmii. So that one can get a view at how big and complex of a task it would be. I was thinking on translating to german, but dont now what to expect.

**Comment by xflak** [comment]
> Hey xflak would you consider putting some guide out for people who want to translate modmii. So that one can get a view at how big and complex of a task it would be. I was thinking on translating to german, but dont now what to expect.
> 
> Nothing crazy just something simple for a vague over view.

Great idea, thanks for reaching out. It prompted me to make this post that I think you will find helpful
[https://gbatemp.net/threads/modmii-how-to-contribute-a-translation.625992/](https://gbatemp.net/threads/modmii-how-to-contribute-a-translation.625992/)
