### ISSUE TITLE
Release files 7.0.1 marked as malicous

### ISSUE THREAD

**Issue by activivan** [modmii/modmii.github.io#5]
Both the installer and the portable zip (release 7.0.1) are marked as malicous by Firefox and Microsoft Defender as well as by the online service VirusTotal (https://www.virustotal.com/gui/file/98018d87aefc3a5d6d56c053a842377e1d4a76d07b01750fc35343c023892811/detection)

![grafik](https://github.com/modmii/modmii.github.io/assets/76850500/942c2521-ee84-4094-a704-563546d5d1e2)

![grafik](https://github.com/modmii/modmii.github.io/assets/76850500/7749f0d2-7866-4f62-9eeb-e0a34ea0db67)

**Comment by xflak** [comment]
False positive. This should be reported on the receiving end not here
