### ISSUE TITLE
Get-Disk.vbs failure not caught

### ISSUE THREAD

**Issue by nroach44** [modmii/modmii.github.io#9]
The launch of Get-Disk.vbs may fail (e.g. it's a common malware vector, and may be blocked) but the tool appears completely oblivious to this failure.

Secondly, is there a reason you're using VBScript to call a batch script to call a powershell & WMI command? Surely this can all be done in PowerShell / .NET etc.?

**Comment by xflak** [comment]
Known harmless bug as per the bottom of the first post here: https://gbatemp.net/threads/best-way-to-mod-any-wii-modmii-for-windows-official-support-thread.207126/

I'll make some tweaks, but the failure is harmless. This part of the script just retrieves hdd format information for connected drives (excl C:) to include in guides so users don't need to manually check for this info
